services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: mqtt_user
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  api:
    build:
      context: ./
    container_name: mqtt-api
    depends_on:
      - postgres
    ports:
      - "5001:80"
    networks:
      - appnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:

networks:
  appnet: